server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 6000
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
    async:
      request-timeout: 50000 #50초
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(WeHNFNKufGitWpnyrsL4ByynpUFh/c+aNou2frtCROYOFQJNTNLFiTviLip5lD8HKy+D5x9W2ftEuJbEX9Uf12IijzFLjwBK3exYwSDY/SZWaYZd0hl/Uz46cY6Wl96mtZloyrFxHKo=)
    username: ENC(RkAz9Pxk+SFvyxWXXpkdQg==)
    password: ENC(/cndnWTpsw7+7fWX7ceqG0GPIwX3zHIB)
  #  s3--
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(TS59x/VA4JVsszIBgTVEq6v20cxygtP/zFhFfhcgeYw7OnEYZCi4iax0rytnVoqu)
            redirect-uri: http://localhost:3000/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client_name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret:
    ENC(gSd1QCnq05LyByOTvaIGKcp+XyHp6M4F3XhfK4xwlPz3BOyp85rUpRKK7GyD0jc0kvMS+1CCgwKsFZrBPN/kkJ6WCJlJRijzA18xOwN8rmFrMFxrLLhn0zKrr8MW5GF+N8UcvTUBF3PfxBnvay8B1WJFh1N4oeGc)
  access-expiration : 1800000 #30분 1800000
  refresh-expiration : 604800000 #1주 604800000
#s3--
cloud:
  aws:
    credentials:
      access-key: ENC(iLxRM7InkH7YNuLWnDePgDev84wNkrNkECl3ByTAJNk=)
      secret-key: ENC(ynyjEzQo24nAHoWrN49TTrh1Jrs+lUNWznWibrvJkaQa8aSM7sRM1zH3L2+Dfj5EE52VrFmS820=)
    region:
      auto: false
      static: ap-northeast-2 #버킷의 리전
    s3:
      bucket: ENC(TjYB3B8CaCdfM9V363RTtaMqu2owcnjo) #버킷 이름
    stack:
      auto: true
#      cloud:stack:auto:false는 AWS Elastic Beanstalk에서 환경 스택을 생성할 때 사용하는 옵션 중 하나입니다.
#      기본적으로 Elastic Beanstalk은 AWS CloudFormation을 사용하여 환경 스택을 자동으로 생성합니다.
#      이때 cloud:stack:auto:true 옵션이 기본값으로 사용되며,
#      이 옵션을 사용하면 Elastic Beanstalk이 CloudFormation 스택을 자동으로 생성하고 관리합니다.
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cacheName:
  getCache: cacheHenein

aws:
  ses:
    from: Helper@henein.kr

apiKey: ENC(A3w4vRd9efUTqFnmP1uK8onHyVTe2w0W40HpsctvL7k=)

google:
  recaptcha:
    key:
      site-key: ENC(5hb559Csyk76+YmgfRoh4ttrnwmWg14rj8kJ2cDj5BxfOQ1eGzwV76q4ntkaifnX7L4kuG8QKOc=)
      secret-key: ENC(9hKur4KynVyU0HzFT85unI6iDrrlkkIoWKSTAXrMfBNP2t5I3rlWNpyLh31hvw00nrOPtLyXU+g=)
      url: https://www.google.com/recaptcha/api/siteverify